# Generated by Django 4.2.3 on 2023-07-21 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journalistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('text', models.TextField(default='')),
                ('news_date', models.DateField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.journalistmodel')),
            ],
        ),
    ]
