# Generated by Django 4.2.3 on 2023-07-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journalistmodel',
            table='journalist',
        ),
        migrations.AlterModelTable(
            name='newsmodel',
            table='news',
        ),
    ]
