# Generated by Django 4.2.3 on 2023-07-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_journalistmodel_table_alter_newsmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='name_en',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='name_ru',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='name_uz',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='text_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='text_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='text_uz',
            field=models.TextField(default='', null=True),
        ),
    ]
